### ISSUE TITLE
FileNotFoundError: './results//encoding_fold_0.csv'

### ISSUE THREAD

**Issue by PascalIversen** [ddhostallero/BiG-DRP#2]
Hi there,
thanks for sharing the code.

If I try to run:
`$ python main.py --mode=extra
`
I get:
`FileNotFoundError: [Errno 2] No such file or directory: './results//encoding_fold_0.csv'
`
Where do I get these encodings?

Thanks

Pascal

**Comment by ddhostallero** [comment]
Hi,

Please run: 
```
python main.py --mode=train
```
before using the ``--mode=extra``.  The ``train`` mode will generate the encodings, as well as the initial model. The ``extra`` mode needs the encodings and the initial model because it is only an extra epoch for stabilization of the prediction layers of the model.

Also,  the ``--weight_folder`` argument in the ``extra`` mode should be equal to the ``--folder`` argument of the ``train`` mode if you manually set it (recommended).

**Comment by PascalIversen** [comment]
Thanks for the quick clarification!
